#!c:\users\pb7n0079\desktop\pip\env\scripts\python.exe

import docx2txt

if __name__ == '__main__':
    import sys
    args = docx2txt.process_args()
    text = docx2txt.process(args.docx, args.img_dir)
    sys.stdout.write(text.encode('utf-8'))
